import 'package:do_it/utils/constants.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:visibility_detector/visibility_detector.dart';

class TaskCard extends StatelessWidget {
  const TaskCard({Key? key, required this.index, required this.isInView}) : super(key: key);

  final int index;
  final bool isInView;



  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: isInView ? 1.0 : 0.4 ,
      child: Container(
        margin: EdgeInsets.only(left: 20.w,right: 20.w,top: 15,bottom: 15),
        width: 320.w,
        height: 52.h,
        decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(10)
        ),
        child: Padding(
          padding:  EdgeInsets.symmetric(horizontal: 12.w),
          child: Row(
            children: [
              iconsList[index >= 5 ? 0 : index],
              SizedBox(width  : 10.w,),
              Flexible(
                child: Text('this is  a task generated by ahmad taleb the best in the world ',style:
                kTaskStyle,overflow: TextOverflow.ellipsis,),

              ),
              SizedBox(width: 10.w,),
              Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text('${index} Jun',style: GoogleFonts.lato(fontWeight: FontWeight.bold,color: Colors.black),),
                  SizedBox(height: 2.h,),
                  Text('asd')

                ],)
            ],
          ),
        ),
      ),
    );
  }
}
