import 'package:do_it/utils/constants.dart';
import 'package:do_it/view/widgets/Common/RoundBlueButton.dart';
import 'package:do_it/view/widgets/drawer/AddButton.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:visibility_detector/visibility_detector.dart';

class TodoCard extends StatelessWidget {
  const TodoCard({Key? key, required this.index, required this.isInView}) : super(key: key);

  final int index;
  final bool isInView;



  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: isInView ? 1.0 : 0.4 ,
      child: Container(
        margin: EdgeInsets.only(left: 20.w,right: 20.w,top: 15,bottom: 15),
        width: 320.w,
        height: 52.h,
        decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(10)
        ),
        child: Material(
          child: Padding(
            padding:  EdgeInsets.symmetric(horizontal: 12.w),
            child: InkWell(
              onTap: (){
                _showDescriptionDialog(context,title: 'Shopping list, food for the week',description: 'Lorem ipsum dolor sit amet, consectetur  ex adipiscingelit, sed do  eiusmod  tempor  incid  idunt  ut  labore  et set  dolore  magna  aliqua.Ut  enim  ad  minim  veniam,  quis  nostrud  esse  cillum dolore  eu  fugiat  nulla  pariatur.  Excepteur  sint occae cat cupidatat non proident, sunt in culpa qui officia.',date: DateTime.now(),icon:  SvgPicture.asset('assets/images/gymIcon.svg'));
            },
              child: Row(
                children: [
                  iconsList[index >= 5 ? 0 : index],
                  SizedBox(width  : 10.w,),
                  Flexible(
                    child: Text('this is  a task generated by ahmad taleb the best in the world ',style:
                    kTaskStyle,overflow: TextOverflow.ellipsis,),

                  ),
                  SizedBox(width: 10.w,),
                  Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Text('${index} Jun',style: GoogleFonts.lato(fontWeight: FontWeight.bold,color: Colors.black),),
                      SizedBox(height: 2.h,),
                      Text('asd')

                    ],)
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  void _showDescriptionDialog(BuildContext context,{required String description,required String title,required DateTime date,required Widget icon}){

      showDialog(context: context, builder: (context){
        return AlertDialog(
          titlePadding: EdgeInsets.only(left: 26.w,right:26.w, top: 18.h),
        title: Column(

          mainAxisSize: MainAxisSize.min,
          children: [
           icon,
            SizedBox(height: 17.h,),
            Text(title,style: GoogleFonts.lato(
              fontSize: 16,
              color: kDateColor,
              fontWeight: FontWeight.bold
            ),),
            SizedBox(height: 5.h,),
            Text('19 june',style: kDateStyle,),


          ],

        ),
          content: Column(
            mainAxisSize: MainAxisSize.min,

            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text('Description',style: kDateStyle),
              SizedBox(height: 18.h,),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                child: Text(description,style: GoogleFonts.lato(
                    color:    Color(0xff95989A),
          letterSpacing: 1,
                  fontWeight: FontWeight.bold,
                    fontSize: 13
                  ,),
              ),

              )],
          ),
          actions: [
            Center(child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 20),
              child: RoundBlueButton(onPressed: () => Navigator.pop(context), text: 'Done',),
            ))
          ],
        );


      });
  }
}
